### PR TITLE
Adds batched_params which is a dictionary of lists of batched paramet…

### PR DESCRIPTION
**Pull request by ejsundstr**
adds batched_params which is a dictionary of lists of batched parameters indexed by parameter name

See the tests for good examples

### CODE REVIEW

**Comment by ejsundstr** [comment]
2.7.5+affirm.1.0.3 == 2.7.5 (tag 2.7.5) but I want to merge into the correct branch name.

**Comment by ejsundstr** [comment]
I'll need to test this on charlotte, but I may just wait until I get batches added to metrics_live since I can test that on stage much easier!

**Comment by gregsterin** [comment]
Is this just patching the batch params stuff to 2.7.5?

**Comment by ejsundstr** [comment]
@gregsterin  Yes that is all.  I forgot to mark as WIP

**Review by gregsterin — APPROVED** [review]

**Pull request merged**
